
Vagrant.configure("2") do |config|
	config.vm.define "centos" do |centos|
	config.vm.box = "centos/7"
	end
	config.vm.define "ubuntu" do |ubuntu|
	ubuntu.vm.box = "ubuntu/bionic64"
	ubuntu.vm.provision "shell",
	inline:
	"apt-get update
	apt-get install -y apache2
	mkdir RUDYK
	cd Rudyk 
	touch Rudyk_file"
	ubuntu.vm.network "forwarded_port", guest:80, host: 8081, host_ip: "127.0.0.1"
	end
end
